pushstartert-rails/config/routes.rb
PushstartertRails::Application.routes.draw do
  resources :projects do
    member do
      patch 'backup'
      patch 'unfreeze'
    end
    collection do
      get 'funded'
      get 'news'
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  root to: "home#index"

end

pushstartert-rails/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all

    if user
      can :change_roles, User, role: 'admin'
      can :unfreeze, User, role: 'admin'
      can :backup, Project
      can :create, Project
      if user.role == 'admin'
        can :manage, Project
      end
      can :manage, Project, user_id: user.id
    end
  end
end

pushstartert-rails/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  before_save :default_values
  
  def default_values
    self.state ||= 'freezed'
  end

  state_machine initial: :freezed do
    event :unfreeze do
      transition freezed: :unfreezed
    end
    event :freeze do
      transition unfreezed: :freezed
    end

    state :freezed
    state :unfreezed
  end
end

pushstartert-rails/app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w[admin user]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable
  has_many :projects
end

pushstartert-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit! }
  end

  private

end

pushstartert-rails/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @projects = Project.find(:all, :order => "id desc", :limit => 5)

  end

end

pushstartert-rails/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  # before_action :set_project, only: [:show, :edit, :update, :destroy]
  # before_action :correct_user, ony: :destroy

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  def news
    @projects = Project.find(:all, order: 'created_at desc')
    render template: '/projects/feed.rss.builder', layout: false
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def backup
    set_project
    @project.funded += params[:value].to_f
    @project.save
    redirect_to @project, notice: 'Project was successfully backed.'
  end

  def funded
    @projects = Project.where('funding_goal <= funded')
  end

  def unfreeze
    set_project
    @project.unfreeze
    @project.save
    respond_to do |format|
      format.json { render action: 'funded' }
    end
    # redirect_to :back
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  protected

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :funding_goal, :funded, :state)
    end

end

pushstartert-rails/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  protected

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :role)
  end
end

pushstartert-rails/app/controllers/user_controller.rb
class UserController < ApplicationController
  load_and_authorize_resource

end

pushstartert-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

pushstartert-rails/app/helpers/home_helper.rb
module HomeHelper
end

pushstartert-rails/app/helpers/projects_helper.rb
module ProjectsHelper
end

pushstartert-rails/app/helpers/user_helper.rb
module UserHelper
end

pushstartert-rails/app/views/home/index.html.haml
%h3 Welcome ~ index

%h4 All last projects
- @projects.each do |project|
  %div
    = link_to project.name, project
    %span= project.funding_goal
    %span= project.funded

pushstartert-rails/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PushstartertRails
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    %h1{style: "font-family: 'Lily Script One', cursive; text-decoration: none;"}
      = link_to 'PushStarter', root_path, {style: "text-decoration: none;"}
    %h2{style: "font-family: 'Lily Script One', cursive;"} Way better than Kickstarter
    %div
      - unless user_signed_in?
        = link_to 'Sign up', new_user_registration_path
        = link_to 'Sign in', new_user_session_path
      //- if user_signed_in?
      //  = link_to 'Token Authentication Example', token_path(auth_token: current_user.authentication_token)
      - if user_signed_in?
        %div
          = current_user.email
          %span ||
          = link_to 'My info', edit_user_registration_path
          = link_to 'Sign out', destroy_user_session_path, method: :delete
          = link_to 'New Project', new_project_path
          %span ||
          - if can? :unfreeze, current_user
            = link_to 'Show funded projects', funded_projects_path

    %hr
    = yield

pushstartert-rails/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :funding_goal %><br>
    <%= f.text_field :funding_goal %>
  </div>
  <div class="field">
    <%= f.label :funded %><br>
    <%= f.text_field :funded %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pushstartert-rails/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

pushstartert-rails/app/views/projects/funded.html.haml
%h2 Funded Projects
- if user_signed_in?
  %ul
    - if can? :unfreeze, current_user
      - @projects.each do |project|
        %li
          %strong= project.name
          %span= project.funding_goal
          %span= project.funded
          - if project.freezed?
            = link_to 'Unfreeze', unfreeze_project_path(project), method: :patch, remote: true

pushstartert-rails/app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Funding goal</th>
      <th>Funded</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.funding_goal %></td>
        <td><%= project.funded %></td>
        <td><%= project.state %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

pushstartert-rails/app/views/projects/index.html.haml
%h1 Listing projects

%table
  %thead
    %tr
      %th Name
      %th Funding goal
      %th Funded
      %th State
      %th
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= project.funding_goal
        %td= project.funded
        %td= project.state
        - if user_signed_in?
          %td= link_to 'Show', project
          - if can? :update, project
            %td= link_to 'Edit', edit_project_path(project)
            %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

pushstartert-rails/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

pushstartert-rails/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Funding goal:</strong>
  <%= @project.funding_goal %>
</p>

<p>
  <strong>Funded:</strong>
  <%= @project.funded %>
</p>

<p>
  <strong>State:</strong>
  <%= @project.state %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

pushstartert-rails/app/views/projects/show.html.haml
%p{id: "notice"}
  = notice

%p
  %strong Name
  = @project.name

%p
  %strong Funding goal:
  = @project.funding_goal

%p
  %strong Funded:
  = @project.funded

%p
  %strong State:
  = @project.state

%p
  %strong By User:
  = @project.user.email

%div
  - if user_signed_in?
    - if can? :update, @project
      = link_to 'Edit', edit_project_path(@project) 
      %span |
    - else
      %ul
        %li
          = link_to 'Backup project - 10.00', backup_project_path(@project, value: 10), method: :patch
        %li
          = link_to 'Backup project - 20.00', backup_project_path(@project, value: 20), method: :patch
        %li
          = link_to 'Backup project - 50.00', backup_project_path(@project, value: 50), method: :patch
        %li
          = link_to 'Backup project - 100.00', backup_project_path(@project, value: 100), method: :patch

  = link_to 'Back', projects_path

pushstartert-rails/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>